# Generated by Django 6.0.4 on 2026-07-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deletion_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
