# Generated by Django 6.0.4 on 2026-05-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postreaction_author_post_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_edit_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
