# Generated by Django 6.0.4 on 2026-05-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_last_edit_datetime_alter_post_creation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creation_date',
            new_name='creation_datetime',
        ),
    ]
