# Generated by Django 6.0.4 on 2026-06-01 08:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_image_alter_post_slug_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postreaction',
            name='created_at',
        ),
        migrations.AddField(
            model_name='postreaction',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
