# Generated by Django 6.0.4 on 2026-04-13 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
