# Generated by Django 6.0.4 on 2026-04-26 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_remove_comment_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='commentreaction',
            constraint=models.UniqueConstraint(fields=('author', 'comment'), name='author_comment_reaction'),
        ),
    ]
