# Generated by Django 6.0.4 on 2026-05-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='creation_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
