# Generated by Django 6.0.4 on 2026-06-01 08:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_remove_comment_creation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreaction',
            name='created_at',
        ),
        migrations.AddField(
            model_name='commentreaction',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
