# Generated by Django 6.0.4 on 2026-06-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_remove_commentreaction_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='last_edit_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
