# Generated by Django 6.0.4 on 2026-06-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0009_comment_last_edit_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
