# Generated by Django 6.0.4 on 2026-07-25 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_deleted',
        ),
    ]
