# Generated by Django 6.1 on 2026-08-14 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creation_datetime',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='deletion_datetime',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='last_edit_datetime',
            new_name='edited_at',
        ),
    ]
