# Generated by Django 6.0.4 on 2026-07-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_edit_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike'), ('Funny', 'Funny'), ('Sad', 'Sad'), ('Angry', 'Angry'), ('Scary', 'Scary')], default='Like', max_length=20)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
